`r if(knitr:::is_latex_output()) '\\appendix'`

`r if(!knitr:::is_latex_output()) '# (APPENDIX) Appendix {-}'`

<!--
If you feel it necessary to include an appendix, it goes here.
-->

#Appendix {-}

```{r table1, echo=FALSE}
options(knitr.kable.NA = '')
table1<-readr::read_csv("table 1.csv", col_types = readr::cols())
table1%>%
knitr::kable(format = "latex", booktabs= T, caption= "Population Demographics")%>%
kable_styling(font_size =  12 , full_width = TRUE)%>%
  pack_rows("Age",2,11, bold= TRUE )%>%
  pack_rows("Race and Ethnicity",12,21, bold= TRUE)%>%
  pack_rows("Gender",22,24, bold= TRUE)%>%
  column_spec(1,width = "6.1cm")%>%
  footnote(general = "Percentages may not add up to 100 because of missing data")

```


<br />
<br />
```{r table2, echo=FALSE}
table2<-readr::read_csv("diabetes_crude_test_Output.csv", col_types = readr::cols())
table2%>%
knitr::kable(format = "latex", booktabs= T, caption= "Crude PHA Regression Model")%>%
  kable_styling(font_size =  12 , full_width = T)%>%
  footnote(general = "Reference groups were Female and AI/AN")

```

```{r table3, echo=FALSE}
table3<-readr::read_csv("Adjusted_Diabetes_PHA_Output.csv", col_types = readr::cols())
table3%>%
knitr::kable(format = "latex", booktabs= T, caption= "Adjusted PHA Regression Model")%>%
  kable_styling(font_size =  12 , full_width = T)
```

```{r table4, echo=FALSE}
table4<-readr::read_csv("pha_agency_output.csv", col_types = readr::cols())
table4%>%
knitr::kable(format = "latex", booktabs= T, caption= "Crude PHA Agency Regression Model")%>%
  kable_styling(font_size =  12 , full_width = T)
```


```{r table5, echo=FALSE}
table5<-readr::read_csv("pha_agency_adj_output.csv", col_types = readr::cols())
table5%>%
knitr::kable(format = "latex", booktabs= T, caption= "Adjusted PHA Agency Regression Model")%>%
  kable_styling(font_size =  12 , full_width = T)%>%
  footnote(general = "Reference groups were Female and AI/AN")
```
