<!--
The {#rmd-basics} text after the chapter declaration will allow us to link throughout the document back to the beginning of Chapter 1.  These labels will automatically be generated (if not specified) by changing the spaces to hyphens and capital letters to lowercase.  Look for the reference to this label at the beginning of Chapter 2.
-->
# Background and Significance {#rmd-basics}
## Public Housing
Housing is widely acknowledged as an important social determinant of health [@Thomson2013]. Health outcomes driven by housing are mediated by housing quality, safety, stability, and affordability [@Taylor2018]. There are well established links between housing quality and morbidity ranging from mental disorders, injuries, infectious diseases, and chronic diseases [@Krieger2002]. There is a growing body of evidence associating substandard and unstable housing with poor health outcomes [@Berkowitz2018 ; @Thomson2013]. However, less understood is the relationship between public housing and health.

The government tries to ameliorate housing problems by providing public housing assistance, which are decent and safe subsidized rental housing for eligible populations including low-income families, the elderly, and persons with disabilities [@HUD2020]. Public housing Authority (PHA) provides several types of housing subsidies that are low income public housuing or voucher-based. A relevant study suggests that people with voucher-based subsidies that move from areas with a high level of poverty to areas with less poverty are associated with a lower prevelance of obesity and diabetes[@Ludwig2011]. Yet, other studies have shown that public housing residents have worse health outcomes than other city residents [@Digenis-Bury2008 ; @Manjarrez2007]. This relationship between public housing assistance in general and chronic conditions such as diabetes is minimally explored.

## Diabetes
Diabetes is a chronic disease that is characterized by an inability of the body to maintain a healthy blood glucose level, this can cause a variety of symptoms that affect multiple systems in the body and can lead to potentially life-threatening complications. The key regulator hormone of glucose is insulin and it is produced in the pancreas. The absence or malfunction of insulin leads to elevated blood glucose levels called hyperglycemia. When insulin hormone is missing or ineffective the disease is called Diabetes Mellitus and this condition has multiple types.

### Diabetes Variants
The most common diabetes variants include type I diabetes mellitus, type II diabetes mellitus, and gestational diabetes. Type I diabetes is usually caused by genetic factors triggering an autoimmune reaction that results in the destruction of insulin producing cells in the pancreas. Also known as Juvenile Diabetes, the type I classification is typically diagnosed relatively early in life during childhood or early adulthood. Whereas Type II diabetes develops when the body can still produce insulin however the amount is insufficient or when the body becomes resistant to the effects of insulin. Type II diabetes is largely attributed to lifestyle factors. Gestational diabetes is the least common type and occurs during pregnancy. The prevalence of type II diabetes is much higher than type I. In the US, type II and type I diabetes account for approximately 91% and 6% of all diagnosed diabetes cases, respectively [@Bullard2018].

Diabetes is a serious chronic condition without a medical cure. The treatment for diabetes involves disease prevention and management. Medical treatment of diabetes primarily consists of exogenous insulin replacement or use of medications that stimulate the pancreas to produce endogenous insulin. Without adequate blood control, diabetes can lead to increased risk of other conditions including vision loss, heart disease, stroke, kidney failure, nerve damage, amputation, and even premature death.

##Problem Definition
Disease management for type II diabetics focuses on lifestyle modification such as diet control and increased physical activity. The goal is to promote weight loss and reduce excess fat that subsequently both reduces insulin resistance and enhances disease control. However, other determinants of health have been recognized to impact the effectiveness of diabetes management, namely healthcare access, cultural and social support, economic stability and built environments [@Clark2014]. Housing instability and food insecurity in particular have been shown to reduce diabetes management self-efficacy for low income adults [@Vijayaraghavan2011]. Providing safe and afforadble housing to those in need may improve overall health and increase diabetes management efficacy.

While there is a growing number of published literature on the correlation between substandard housing and health outcomes, few studies specifically examine the relationship between general public housing support and diabetes status. For this reason, the current study aimed to explore this public health issue within a local context in King County, WA.

In the effort to decrease the gap of knowledge between the junction of public housing and health, Public Health Seattle and King County (PHSKC) developed a unique partnership with King County Housing Authority (KCHA) and Seattle Housing Authority (SHA). This partnership enabled data to be shared across sectors with the intention of informing and measuring future interventions that would improve the health of the county residents. This project expands on the original research from this collaboration revolving around health and public housing. This current research aims to use the provided data to contribute to the literature on the association between public housing and diabetes among Medicaid and Medicare patients.

The findings of the study could help identify where resources for diabetes prevention and management might be used more effectively. For instance, PHAs can look into directly implementing diabetes prevention programs within PHA run housing communities to reduce the burden of diabetes. Furthermore, identifying populations with higher needs of diabetes related care can be used as a metric for implementing health policy.    
