# Discussion {}
##Discussion
Findings from this study indicate that public housing assistance was positively associated with diabetes status. After adjusting for potential confounders (age, gender, race and ethnicity) the results indicate that the effect of public housing on diabetes status increased even greater. The findings also suggest that when stratified into PHA agency in the crude model, KCHA residents where were less likely to meet the definition of diabetes than SHA residents but still more likely than the non-PHA group.  However, after adjust for potential confounders, the effect of association between PHA agency on diabetes status saw a greater increase for KCHA residents than SHA residents.  

The increased risk of diabetes observed in this study in relation to public housing had similar results to another study that compared public housing residents in Boston, MA to other city residents for health outcomes including diabetes that revealed worse health outcomes for public housing residents [@Digenis-Bury2008]. A potential explanation of these findings may be attributed to the fact that public housing residents were more likely to be racial and ethnic minorities and the prevalence of diabetes is often greater for racial and ethnic populations [@Chow2012]. Another possible explanation is that areas and neighborhoods with a high level of poverty, such as where public housing properties may be located tend to also have a higher prevalence of obesity and diabetes [@Ludwig2011].

These findings suggest that public housing residents have a greater need for diabetes treatment and could be an avenue in which resources on diabetes prevention and management may be more effective. A health promotion intervention that utilized homecare nurses to implement a diabetes prevention program in public housing communities proved to be successful and can be a viable option in improving health outcomes [@Whittemore2014]. Considering the population demographics in the PHA group, another successful strategy may be to implement a culturally competent diabetes care intervention program [@Zeh2012].

In contrast, the preliminary findings in this study that suggests that PHA recipients are more likely to be diabetic are inferential and therefore cannot be interpreted as a causal relationship. As previously mentioned, substandard and unstable housing has been linked with worse diabetes health outcomes, however stable housing provided by PHA has been associated with the ability for participants to afford diabetes-related financial expenses [@Keene2018]. Additionally, when housing needs are met participants are able to prioritize diabetes self-management, avoiding potential complications [@Keene2018]. Those participants with diabetes prior to receiving public housing assistance could potentially see a reduction in diabetes related complications over time.
<br />
<br />
<br />
Strengths of this study include the population-based study design that allows for estimation of disease impact on a broad scale and the well-defined study population. The data used in this study were also from reliable sources with careful and normally complete documentation, subsequently reducing the impact of information bias.

## Limitations
There are several limitations to note. First, there may have been unmeasured potential confounders that have not been included in the analyses. Other elements that are recognized to be potential confounders for diabetes may have been useful to include in this study like socioeconomic status and other health characteristics like BMI. Given the obtained data, these elements were not available thus not accounted in this study.      

Another limitation is that this study does not provide the prevalence of diabetes due to the inherent characteristic of claims data. The population captured in the study were only those that sought healthcare services for diabetes care or diabetes related outcomes. People who may have been diabetic during this period but were asymptomatic or those who had been previously diagnosed with diabetes but did not seek care within the time frame provided by the CCW algorithm definition of diabetes were not captured in the study. Consequently, the eligible population in this study cannot provide a prevalence estimate by themselves.

Despite the limitations, this study contributes to our understanding of government subsidized housing and diabetes self-management the findings are generalizable to low-income, racially, and ethnically diverse populations with diabetes who obtain health care in safety-net health settings. More specifically, these findings provide estimates for those with diabetes in public housing and can be used to inform and evaluate existing interventions as well as create new strategies for health promotion within this population. Future studies should continue investigating the relationship between public housing and diabetes and in particular further studies should explore the association over a longer time period.
