# Methods {}
## Study Setting and Study Design
The current study investigates whether public housing is associated with risk of diabetes status among King County, WA residents who were enrolled in Medicare and Medicaid. This study uses a descriptive cross-sectional design. The cross-sectional design is appropriate because it allows for an estimate of a dichotomous disease outcome at a particular point in time [@Greenland1988].

The analysis of this study was conducted on a dataset compiled from the King County _Data Across Sectors for Housing and Health (DASHH)_ partnership. The findings from the original initial study have previously been reported [@PHSKC2018].

## Data Sources
In an effort to reduce fragmented data siloes across different sectors, the DASHH partnership was formed in 2016 between Public Health - Seattle and King County, and two public housing authories, King County Housing Authority and Seattle Housing Authority. The primary objectives for DASHH were to join health and housing administrative data together to inform and measure future interventions, relating to policy, outreach, and program evaluation that would improve the health of King County residents, as well as to disseminate actionable data to key health and housing stakeholders.

KCHA provides housing assistance to families and individuals that earn less than the county median income to approximately 55,000 people in the King County area excluding the cities of Seattle and Renton. While SHA predominatly focuses on people within Seattle, with nearly 35,000 people scattered throughout 400 sites across the city.

The housing data originated from both KCHA and SHA extracted from a standradized US Department of Housing and Urban Development (HUD) form. This data source contained elements that included demographic information and period of enrollment for families and individuals. Claims and enrollment data for Medicaid and Medicare were provided by the Washington Health Care Authority (HCA) and the WA Office of Financial Management, respectively. Enrollment data contained information on who was receiving health insurance benefits. Claims data provided elements such as diagnosis codes and these were used to identify acute events and chronic conditions. The separated health and housing data sources were linked together probabilistically to create a unique identifier. Further detail on the process of joining data can be found in the King County Data Across Sectors for Housing and Health, 2018 Report [@PHSKC2018]. This report provides a detailed technical process of linking Medicaid data, but this approach was similar to both Mediaid and Medicare data used for this study.

## Study Population
The study population was participants that were enrolled in either Medicare or Medicaid programs. Further eligibility for study participation included King County, Washington residency and at least 11 months of Medicare or Medicaid coverage in 2017. The 11 month minimum coverage restriction provides a more complete picture of healthcare usage in 2017, reducing the artifical inflation of the eligble population with people that had little chance of meeting the diabetes definiton. The overall number of participants derived from the DASHH dataset totaled 585,372.

### Exposure Variable
The exposure variable for this study was public housing assistance status. This was extracted from the HUD-50058 form which was provided by the PHAs. The HUD-50058 form provides information on families that participate in public housing or Section 8 rental subsidy programs [@HUD2020]. Housing assistance is separated into 3 main types:

* Housing Choice Vouchers - vouchers provided to recipients to rent units on the private housing market
* Public housing properties and units - subsidized housing managed by PHAs
* Project-based vouchers - subsidized housing units not managed by PHAs

Responses on the HUD-50058 form were combined into a composite public housing binary variable. Study participants that were not enrolled in any of the listed housing assistance programs were not placed in the PHA category. Whereas any of the 3 types of housing assistance were categorized into the PHA group.

### Outcome Variable
The outcome variable for this study was diabetes status. This was defined using the Centers for Medicare and Medicaid Services (CMS) Chronic Conditions Warehouse (CCW) algorithm [@CMS2020]. According to the CCW, a participant meets the criteria if they have at least 1 inpatient, skilled nursing facility, home health agency visit or 2 hospital outpatient or carrier claims with diabetes diagnoses codes as outlined by the chronic conditions reference list within the last 2 years[@CMS2020]. This definition does not specify diabetes variant but instead accounts for any type diabetes diagnoses. The diabetes status outcome variable was dichotomous.

### Potential Confounders
Potential confounders were identified based on literature review. This study considers age, race and ethnicity and gender as potential confounding variables. Each of these variables were selected due to the increased baseline risk for participants to be either in public housing or have diabetes. It is known that diabetes is an age-related disease, with a higher risk for older populations [@Selvin2013]. Age was presented as a discrete variable for the participants age in 2017. Similarly, according to CDC data, racial minority groups may be differentially at risk for both type 1 and type 2 diabetes compared to their white counterparts [@Divers2020 ; @CDC2020]. Although the discrete variable for age was used in the statistical analyses, age is presented ategorically in the descriptive analyses for a simpler distribution description. Mean and median age were also shown for each category. Race and ethnicity variable was defined categorically and included: American Indians/Alaska Natives, Asian, Asian Pacific Islander, Black/African American, Latino, Multiple, Native Hawaiian and Pacific Islander, Other, Unknown, and White. Due to the limitations of the how Medicare data categorizes race, this study categorized Asian Pacific Islander as a distinct group from the other seperate groups of Asian and Native Hawaiian and Pacific Islander. Gender was selected because both psychosocial and biological factors are responsible for sex and gender diabetes risk differences [@Kautzky-Willer2016]. Gender was grouped categorically and included: Female, Male, and Multiple.

## Analyses
For the statistical analyses, logistic regression models were fitted to assess the risk of diabetes status in relation to public housing assistance status. This analysis is well-suited for this study because logistic regression analyses allows for measuring the association of an effect towards a binomial response variable by combining multiple variables to avoid confounding [@Sperandei2014].

There were two main research questions in this study. The primary research question dwelved into the relationship between public housing assistance and diabetes. The secondary question looked into the relationship between each of the public housing authorities and diabetes status. The distinction between these analyses are that first provides the likelihood of meeting the diabetes definiton if a person was receiving public housing assistance and the second provides a more specific estimate for each of the housing authority.

Crude and adjusted models were fitted to answer the research questions. The adjusted model accounted for age race and ethinicity and gender variables.The models were used to determine the odds ratios (OR) and corresponding 95% confidence intervals. Findings were statistically significant if the estimates did not cross the confidence intervals and p-values were below <0.05 threshold. Analyses were conducted using statistical software R and RStudio version 3.6.0.
