
# Results {#ref-labels}

Among the study participants, the proportion of people in the PHA group were 10.4% and of that, 5.9% were with KCHA and 4.6% with SHA. The majority, 89.5% did not have any public housing assitance in 2017. Overall, 9.9% were considered to meet the definiton of diabetes and the rest, 90.1% were not considered to have diabetes.



```{r, echo=FALSE}
options(knitr.kable.NA = '')
table1<-readr::read_csv("table 1.csv", col_types = readr::cols())
table1%>%
knitr::kable(format = "latex", booktabs= T, caption= "Population Demographics")%>%
  kable_styling(latex_options = "striped", full_width = T)%>%  
  pack_rows("Age",2,11, bold= T )%>%
  pack_rows("Race and Ethnicity",12,21, bold= T)%>%
  pack_rows("Gender",22,24, bold= T)%>%
  column_spec(1,width = "6.1cm")%>%
  footnote(general = "Percentages may not add up to 100 because of missing data")
```


For the first analysis, the assocation between diabetes status and public housing assistance, in unadjusted model the odds ratio of having diabetes was 1.34 fold greater (95% CI: 1.31-1.38) for those with public housing assistance (table 2). In the adjusted model, PHA residents were 63% more likely to meet the definition of diabetes compared to those that were non-PHA residents.

Status  | Model 1          | Model 2
--------|------------------|----------------
Non-PHA | 1                | 1
PHA     | 1.34 (1.31-1.38) | 1.92 (1.58-2.45)

In the second analysis, the association between diabetes status and the specific public housing authorities, the crude model showed that the odds of meeting the definiton of diabetes were 1.28 times greater (95% CI: 1.24-1.33) among KCHA residents and 1.42 (95% CI: 1.38-1.48) times greater among SHA residents. The adjusted model showed, that among KCHA residents the odds of meeting the definition of diabetes were 2.16 (95% CI: 2.09-2.25) times higher and 1.70 (95% CI: 1.64-1.77) for SHA residents compared to non-PHA residents. 













#

By far the easiest way to present tables in your thesis is to store the contents of the table in a CSV or Excel file, then read that file in to your R Markdown document as a data frame. Then you can style the table with the `kable` function, or functions in the [kableExtra](https://cran.r-project.org/web/packages/kableExtra/index.html) pacakge.

In addition to the tables that can be automatically generated from a data frame in **R** that you saw in [R Markdown Basics] using the `kable` function, you can also create tables using _pandoc_. (More information is available at <http://pandoc.org/README.html#tables>.)  This might be useful if you don't have values specifically stored in **R**, but you'd like to display them in table form.  Below is an example.  Pay careful attention to the alignment in the table and hyphens to create the rows and columns. Generally I don't recommend this approach of typing the table directly into your R Markdown document.

----------------------------------------------------------------------------------
  Factors                    Correlation between Parents & Child      Inherited
------------------------- ----------------------------------------- --------------
  Education                                -0.49                         Yes

  Socio-Economic Status                     0.28                        Slight   

  Income                                    0.08                          No

  Family Size                               0.18                        Slight

  Occupational Prestige                     0.21                        Slight
------------------------- ----------------------------------------- --------------
Table: (\#tab:inher) Correlation of Inheritance Factors for Parents and Child

We can also create a link to the table by doing the following: Table \@ref(tab:inher).  If you go back to [Loading and exploring data] and look at the `kable` table, we can create a reference to this max delays table too: Table \@ref(tab:maxdelays). The addition of the `(\#tab:inher)` option to the end of the table caption allows us to then make a reference to Table `\@ref(tab:label)`. Note that this reference could appear anywhere throughout the document after the table has appeared.  
