---
# UW thesis fields
title: "Diabetes and Public Housing"
author: "Marc Macarulay"
year: "2020"
program: "Health Services"
chair:
chairtitle:
Committee :

abstract: |
  Public housing residents have worse health than the general population including chronic diseases such as diabetes. Knowledge of which specific populations within public housing residents have chronic conditions is essential for public health agencies to implement efficient health promotion programs. This cross-sectional design study was conducted using data collected from Data Across Sectors for Housing and Health partnership in King County, WA. Total population included were Medicaid and Medicare beneficiaries compiled from Washington Health Care Authority (n= 585,372). Associations between public housing and diabetes status were estimated using odds ratios and corresponding 95% confidence intervals from crude and adjusted models. Further associations were determined between individual public housing authorities and diabetes status using the same crude and adjusted models. Among study participants 10.4% received some form public housing assistance in 2017. In total, 9.9% were considered to have diabetes. The adjusted model revealed that public housing residents were 1.94 times (95% CI: 1.88-1.99) more likely to meet the diabetes definition compared to those not receiving housing assistance. These findings suggest that public housing residents are more likely to be diabetic. Further studies should explore the relationship between public housing and diabetes over a longer period to discern the direction of the association over time. Findings from this study can be used to inform future interventions for diabetes treatment by both public health and housing agencies.
acknowledgments: |
  "My acknowledgments"
# End of UW thesis fields
knit: "bookdown::render_book"
site: bookdown::bookdown_site
output:
  huskydown::thesis_pdf:
    latex_engine: xelatex
#  huskydown::thesis_gitbook: default
#  huskydown::thesis_word: default
#  huskydown::thesis_epub: default
bibliography: bib/M.bib
# Download your specific bibliography database file and refer to it in the line above.
csl: csl/apa.csl
# Download your specific csl file and refer to it in the line above.
lot: true
lof: true
# space_between_paragraphs: true
# Delete the # at the beginning of the previous line if you'd like
# to have a blank new line between each paragraph
#header-includes:
#- \usepackage{tikz}
---

<!--
Above is the YAML (YAML Ain't Markup Language) header that includes a lot of metadata used to produce the document.  Be careful with spacing in this header!

If you'd like to include a comment that won't be produced in your resulting file enclose it in a block like this.
-->

<!--
If you receive a duplicate label error after knitting, make sure to delete the index.Rmd file and then knit again.
-->

```{r include_packages, include = FALSE}
# This chunk ensures that the huskydown package is
# installed and loaded. This huskydown package includes
# the template files for the thesis.
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")
if(!require(huskydown))
  devtools::install_github("benmarwick/huskydown")
library(huskydown)
```

```{r load-packages, include=FALSE}
library(dplyr)
library(magrittr)
library(knitr)
library(kableExtra)
library(xtable)
```
<!-- The {.unnumbered} option here means that the introduction will be "Chapter 0." You can also use {-} for no numbers on chapters. -->
